# Generated by Django 3.2.6 on 2022-11-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan_It_Teknoy', '0016_merge_20221129_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentgen',
            name='doc_file',
            field=models.FileField(default='Not set', null=True, upload_to='docs/'),
        ),
    ]
