# Generated by Django 3.2.6 on 2022-12-12 07:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan_It_Teknoy', '0017_documentgen_doc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentgen',
            name='doc_file',
            field=models.FileField(default='Not set', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media', location='/media/'), upload_to='docs/'),
        ),
    ]
